debug: false

# 服务端配置
server:
  # 端口号
  port: 8888
  # servlet 上下文路径
  servlet:
    context-path: /

# spring配置
spring:
  # 项目名称
  application:
    name: shiroJsp
  #  mvc 为 jsp
  mvc:
    view:
      prefix: /
      suffix: .jsp
  # mysql数据库配置信息
  datasource:
    username: root
    password: bsy8023.00
    url: jdbc:mysql://localhost:3306/shiro?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid 数据库连接池
    type: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接等待超时的时间  毫秒
      max-wait: 60000
      # 闭空闲连接的检测时间间隔  毫秒
      time-between-eviction-runs-millis: 60000
      # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 验证数据库服务可用性的sql.用来检测连接是否有效的sql
      validation-query: SELECT 1 FROM DUAL
      # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效
      test-while-idle: true
      # 申请连接时直接检测连接是否有效
      test-on-return: false
      # 归还连接时检测连接是否有效
      test-on-borrow: false
      # 开启PSCache
      pool-prepared-statements: true
      # 设置PSCache值
      max-pool-prepared-statement-per-connection-size: 20
      # 数据库服务宕机自动重连机制
      break-after-acquire-failure: true
      # 连接出错后重试时间间隔
      time-between-connect-error-millis: 300000
      # 异步初始化策略
      async-init: true
      # 是否自动回收超时连接
      remove-abandoned: true
      # 超时时间(以秒数为单位)
      remove-abandoned-timeout: 1800
      # 事务超时时间
      transaction-query-timeout: 6000
      # 打开mergeSql功能,慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true

      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.wyl.service.*

      # 配置监控统计拦截的filters，  stat:监控统计、log4j：日志记录、wall：防御sql注入
      filters: stat,wall
      filter:
        # stat:监控统计
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        # wall：防御sql注入
        wall:
          enabled: true
          config:
            drop-table-allow: false

      # 配置监控页功能
      stat-view-servlet:
        # 开启
        enabled: true
        # 配置DruidStatViewServlet
        url-pattern: /druid/*
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 监控页面登录的用户名
        login-username: 'pepsi-wyl'
        # 监控页面登录的密码
        login-password: '000000'
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny:

      # 监控web
      web-stat-filter:
        # 开启
        enabled: true
        # 监控路径
        url-pattern: /*
        # 排除的路径
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name: session_name
        principal-cookie-name: cookie_name
  # redis
  redis:
    host: 101.43.169.194
    port: 6379
    password: bsy8023.00
    database: 0
    # jedis
    client-type: jedis
    jedis:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0

# mybatis-plus 配置
mybatis-plus:
  configuration:
    # 日志配置信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 包扫描别名
  type-aliases-package: com.pepsiwyl.pojo
  # mapper文件
  mapper-locations: classpath*:/mapper/**/*.xml

